In [1]:
import sklearn.datasets
import numpy as np

In [3]:
cancer_ds = sklearn.datasets.load_breast_cancer()

In [4]:
#lets organise as X and Y
X = cancer_ds.data
Y = cancer_ds.target

In [5]:
print(X)
print(Y)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 

In [6]:
print(X.shape, Y.shape)

(569, 30) (569,)


In [7]:
#get dataset inside a dataframe
import pandas as pd
data = pd.DataFrame(cancer_ds.data, columns = cancer_ds.feature_names)

In [8]:
#rename the Y variable as Target
data['class'] = cancer_ds.target

In [9]:
#examine the first few records
data.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  class  
0          0.4601                  0.11890      0  
1          0.2750                  0.08902      0  
2          0.3613                  0.08758      0  
3          0.6638                  0.17300      0  
4          0.2364                  0.07678      0  

[5 rows x 31 columns]

# Describe function

Generate descriptive statistics

For numeric data, the result’s index will include count, mean, std, min, max as well as lower, 50 and upper percentiles. By default the lower percentile is 25 and the upper percentile is 75. The 50 percentile is the same as the median.

For object data (e.g. strings or timestamps), the result’s index will include count, unique, top, and freq. The top is the most common value. The freq is the most common value’s frequency. Timestamps also include the first and last items.

For mixed data types provided via a DataFrame, the default is to return only an analysis of numeric columns.

If the value of standard deviation is low then it resembles that max value is near avg value and if std is very high then it resembles high variation in data values.

25 percentile resembles that 25% of all data values is less than 11.700 for mean radius and similarly for all other columns.

In [96]:
data.describe()

mean radius  mean texture  mean perimeter    mean area  \
count   569.000000    569.000000      569.000000   569.000000   
mean     14.127292     19.289649       91.969033   654.889104   
std       3.524049      4.301036       24.298981   351.914129   
min       6.981000      9.710000       43.790000   143.500000   
25%      11.700000     16.170000       75.170000   420.300000   
50%      13.370000     18.840000       86.240000   551.100000   
75%      15.780000     21.800000      104.100000   782.700000   
max      28.110000     39.280000      188.500000  2501.000000   

       mean smoothness  mean compactness  mean concavity  mean concave points  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       mean symmetry  mean fractal dimension  ...  worst texture  \
count     569.000000              569.000000  ...     569.000000   
mean        0.181162                0.062798  ...      25.677223   
std         0.027414                0.007060  ...       6.146258   
min         0.106000                0.049960  ...      12.020000   
25%         0.161900                0.057700  ...      21.080000   
50%         0.179200                0.061540  ...      25.410000   
75%         0.195700                0.066120  ...      29.720000   
max         0.304000                0.097440  ...      49.540000   

       worst perimeter   worst area  worst smoothness  worst compactness  \
count       569.000000   569.000000        569.000000         569.000000   
mean        107.261213   880.583128          0.132369           0.254265   
std          33.602542   569.356993          0.022832           0.157336   
min          50.410000   185.200000          0.071170           0.027290   
25%          84.110000   515.300000          0.116600           0.147200   
50%          97.660000   686.500000          0.131300           0.211900   
75%         125.400000  1084.000000          0.146000           0.339100   
max         251.200000  4254.000000          0.222600           1.058000   

       worst concavity  worst concave points  worst symmetry  \
count       569.000000            569.000000      569.000000   
mean          0.272188              0.114606        0.290076   
std           0.208624              0.065732        0.061867   
min           0.000000              0.000000        0.156500   
25%           0.114500              0.064930        0.250400   
50%           0.226700              0.099930        0.282200   
75%           0.382900              0.161400        0.317900   
max           1.252000              0.291000        0.663800   

       worst fractal dimension       class  
count               569.000000  569.000000  
mean                  0.083946    0.627417  
std                   0.018061    0.483918  
min                   0.055040    0.000000  
25%                   0.071460    0.000000  
50%                   0.080040    1.000000  
75%                   0.092080    1.000000  
max                   0.207500    1.000000  

[8 rows x 31 columns]

In [97]:
data['mean radius'].describe() # describe function on a single column

count    569.000000
mean      14.127292
std        3.524049
min        6.981000
25%       11.700000
50%       13.370000
75%       15.780000
max       28.110000
Name: mean radius, dtype: float64

In [94]:
#how many malignant and benign?
print(data['class'].value_counts()) #binary variable either 1 or 0

1    357
0    212
Name: class, dtype: int64


In [12]:
#know the target names
print(cancer_ds.target_names)

['malignant' 'benign']


# Groupby one column and return the mean of the remaining columns in each group

Group DataFrame using a mapper or by a Series of columns.

A groupby operation involves some combination of splitting the object, applying a function, and combining the results. This can be used to group large amounts of data and compute operations on these groups.

In [13]:
data.groupby('class').mean()

mean radius  mean texture  mean perimeter   mean area  mean smoothness  \
class                                                                           
0        17.462830     21.604906      115.365377  978.376415         0.102898   
1        12.146524     17.914762       78.075406  462.790196         0.092478   

       mean compactness  mean concavity  mean concave points  mean symmetry  \
class                                                                         
0              0.145188        0.160775             0.087990       0.192909   
1              0.080085        0.046058             0.025717       0.174186   

       mean fractal dimension  ...  worst radius  worst texture  \
class                          ...                                
0                    0.062680  ...     21.134811      29.318208   
1                    0.062867  ...     13.379801      23.515070   

       worst perimeter   worst area  worst smoothness  worst compactness  \
class                                                                      
0           141.370330  1422.286321          0.144845           0.374824   
1            87.005938   558.899440          0.124959           0.182673   

       worst concavity  worst concave points  worst symmetry  \
class                                                          
0             0.450606              0.182237        0.323468   
1             0.166238              0.074444        0.270246   

       worst fractal dimension  
class                           
0                     0.091530  
1                     0.079442  

[2 rows x 30 columns]

# First grouping based on "class", Within each class we are grouping based on "mean area" 

In [89]:
data.groupby(['class','mean area']).mean()

mean radius  mean texture  mean perimeter  mean smoothness  \
class mean area                                                               
0     361.6            11.08         18.83           73.30          0.12160   
      371.1            10.95         21.35           71.90          0.12270   
      386.1            11.42         20.38           77.58          0.14250   
      431.1            11.76         18.14           75.00          0.09968   
      432.0            11.80         16.58           78.99          0.10910   
...                      ...           ...             ...              ...   
1     800.0            16.14         14.86          104.30          0.09495   
      819.8            16.30         15.70          104.70          0.09427   
      838.1            16.50         18.29          106.60          0.09686   
      880.2            16.84         19.46          108.40          0.07445   
      992.1            17.85         13.23          114.60          0.07838   

                 mean compactness  mean concavity  mean concave points  \
class mean area                                                          
0     361.6               0.21540         0.16890              0.06367   
      371.1               0.12180         0.10440              0.05669   
      386.1               0.28390         0.24140              0.10520   
      431.1               0.05914         0.02685              0.03515   
      432.0               0.17000         0.16590              0.07415   
...                           ...             ...                  ...   
1     800.0               0.08501         0.05500              0.04528   
      819.8               0.06712         0.05526              0.04563   
      838.1               0.08468         0.05862              0.04835   
      880.2               0.07223         0.05150              0.02771   
      992.1               0.06217         0.04445              0.04178   

                 mean symmetry  mean fractal dimension  radius error  ...  \
class mean area                                                       ...   
0     361.6             0.2196                 0.07950        0.2114  ...   
      371.1             0.1895                 0.06870        0.2366  ...   
      386.1             0.2597                 0.09744        0.4956  ...   
      431.1             0.1619                 0.06287        0.6450  ...   
      432.0             0.2678                 0.07371        0.3197  ...   
...                        ...                     ...           ...  ...   
1     800.0             0.1735                 0.05875        0.2387  ...   
      819.8             0.1711                 0.05657        0.2067  ...   
      838.1             0.1495                 0.05593        0.3389  ...   
      880.2             0.1844                 0.05268        0.4789  ...   
      992.1             0.1220                 0.05243        0.4834  ...   

                 worst radius  worst texture  worst perimeter  worst area  \
class mean area                                                             
0     361.6             13.24          32.82            91.76       508.1   
      371.1             12.84          35.34            87.22       514.0   
      386.1             14.91          26.50            98.87       567.7   
      431.1             13.36          23.39            85.10       553.6   
      432.0             13.74          26.38            91.93       591.7   
...                       ...            ...              ...         ...   
1     800.0             17.71          19.58           115.90       947.9   
      819.8             17.32          17.76           109.80       928.2   
      838.1             18.13          25.45           117.20      1009.0   
      880.2             18.22          28.07           120.30      1032.0   
      992.1             19.82          18.42           127.10      1210.0   

                 worst

# Groupby one column and return the mean of only particular column in the group

In [76]:
data.groupby('mean area')['class'].mean()

mean area
143.5     1.0
170.4     1.0
178.8     1.0
181.0     1.0
201.9     1.0
         ... 
1878.0    0.0
2010.0    0.0
2250.0    0.0
2499.0    0.0
2501.0    0.0
Name: class, Length: 539, dtype: float64

# train test split

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X = data.drop('class', axis=1)
Y = data['class']

In [83]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.1, stratify = Y, random_state = 42) # Magical funtion

In [77]:
print(Y.shape, Y_train.shape, Y_test.shape)

(569,) (512,) (57,)


In [78]:
print(X.shape, X_train.shape, X_test.shape)

(569, 30) (512, 30) (57, 30)


# random_state

If there is no random_state provided the system will use a random_state that is generated internally. So, when we run the program multiple times we might see different train/test data points and the behavior will be unpredictable. In case, we have an issue with our model we will not be able to recreate it as we do not know the random number that was generated when we ran the program.

In [47]:
Y_train # Without random state

263    0
434    1
320    1
474    1
416    1
      ..
273    1
52     1
114    1
398    1
502    1
Name: class, Length: 512, dtype: int32

In [60]:
Y_train # Another epoch Without random state

20     1
55     1
467    1
136    1
354    1
      ..
266    1
512    0
377    1
423    1
255    0
Name: class, Length: 512, dtype: int32

To avoid getting different values for train and test every time, we use random_state. This will also have an impact on the evaluation metrics as if the random_state is not selected the values from the evaluation will differ. The values of random_state variable can be any integer, 0 and 1 are the most common values used. You can select your own value. Assume it as a shuffle of cards were, after the first shuffle that's random state 1 the after the second shuffle that's random state 2 etc.

In [57]:
Y_train # With random_state = 10

535    0
338    1
503    0
26     0
158    1
      ..
350    1
357    1
206    1
560    1
416    1
Name: class, Length: 512, dtype: int32

In [58]:
Y_train # Another epoch With random_state = 10, we will get the same set of values

535    0
338    1
503    0
26     0
158    1
      ..
350    1
357    1
206    1
560    1
416    1
Name: class, Length: 512, dtype: int32

In [62]:
Y_train # With random_state = 42

413    1
517    0
245    1
102    1
28     0
      ..
509    0
230    0
354    1
103    1
248    1
Name: class, Length: 512, dtype: int32

In [63]:
Y_train # Another epoch With random_state = 42

413    1
517    0
245    1
102    1
28     0
      ..
509    0
230    0
354    1
103    1
248    1
Name: class, Length: 512, dtype: int32

# Stratify

Stratify parameter makes a split so that the proportion of values in the sample produced will be the same as the proportion of values provided to parameter stratify.

For example, if variable y is a binary categorical variable with values 0 and 1 and there are 25% of zeros and 75% of ones, stratify = y will make sure that your random split has 25% of 0's and 75% of 1's.

Suppose a scenario in which you have 100 binary(0,1) datasets of a cancer patient and you have splitted it into 80% as train_data and 20% as test_data. And by default in test_data, you get 15 values as " 1 " and 5 values as 0, So it will be a quite biased data_set. In order to avoid this situation, we use "stratify" to provide a set of common relationship between training and testing dataset

In [85]:
Y.value_counts() # Ratio of 1 is to 0 in Y is 1.6

1    357
0    212
Name: class, dtype: int64

With Stratify

In [86]:
Y_train.value_counts() #with startify
                      # Ratio of 1 is to 0 in Y_train is 1.6

1    321
0    191
Name: class, dtype: int64

In [87]:
Y_test.value_counts() # Ratio of 1 is to 0 in Y_test is 1.6

1    36
0    21
Name: class, dtype: int64

Without Stratify

In [74]:
Y_train.value_counts() #without startify
                      # Ratio of 1 is to 0 in Y_train is 1.6

1    317
0    195
Name: class, dtype: int64

In [75]:
Y_test.value_counts() # Ratio of 1 is to 0 in Y_test is 2.3

1    40
0    17
Name: class, dtype: int64

If we dont use stratify variable then we get the composition of the train and test sets differ, and this is not desirable and it makes the data biased