In [1]:
import sklearn.datasets
import numpy as np

In [3]:
cancer_ds = sklearn.datasets.load_breast_cancer()

In [4]:
#lets organise asX and Y
X = cancer_ds.data
Y = cancer_ds.target

In [5]:
print(X)
print(Y)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 

In [6]:
print(X.shape, Y.shape)

(569, 30) (569,)


In [7]:
#get dataset inside a dataframe
import pandas as pd
data = pd.DataFrame(cancer_ds.data, columns = cancer_ds.feature_names)

In [8]:
#rename the Y variable as Target
data['class'] = cancer_ds.target

In [9]:
#examine the first few records
data.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  class  
0          0.4601                  0.11890      0  
1          0.2750                  0.08902      0  
2          0.3613                  0.08758      0  
3          0.6638                  0.17300      0  
4          0.2364                  0.07678      0  

[5 rows x 31 columns]

In [10]:
data.describe()

mean radius  mean texture  mean perimeter    mean area  \
count   569.000000    569.000000      569.000000   569.000000   
mean     14.127292     19.289649       91.969033   654.889104   
std       3.524049      4.301036       24.298981   351.914129   
min       6.981000      9.710000       43.790000   143.500000   
25%      11.700000     16.170000       75.170000   420.300000   
50%      13.370000     18.840000       86.240000   551.100000   
75%      15.780000     21.800000      104.100000   782.700000   
max      28.110000     39.280000      188.500000  2501.000000   

       mean smoothness  mean compactness  mean concavity  mean concave points  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       mean symmetry  mean fractal dimension  ...  worst texture  \
count     569.000000              569.000000  ...     569.000000   
mean        0.181162                0.062798  ...      25.677223   
std         0.027414                0.007060  ...       6.146258   
min         0.106000                0.049960  ...      12.020000   
25%         0.161900                0.057700  ...      21.080000   
50%         0.179200                0.061540  ...      25.410000   
75%         0.195700                0.066120  ...      29.720000   
max         0.304000                0.097440  ...      49.540000   

       worst perimeter   worst area  worst smoothness  worst compactness  \
count       569.000000   569.000000        569.000000         569.000000   
mean        107.261213   880.583128          0.132369           0.254265   
std          33.602542   569.356993          0.022832           0.157336   
min          50.410000   185.200000          0.071170           0.027290   
25%          84.110000   515.300000          0.116600           0.147200   
50%          97.660000   686.500000          0.131300           0.211900   
75%         125.400000  1084.000000          0.146000           0.339100   
max         251.200000  4254.000000          0.222600           1.058000   

       worst concavity  worst concave points  worst symmetry  \
count       569.000000            569.000000      569.000000   
mean          0.272188              0.114606        0.290076   
std           0.208624              0.065732        0.061867   
min           0.000000              0.000000        0.156500   
25%           0.114500              0.064930        0.250400   
50%           0.226700              0.099930        0.282200   
75%           0.382900              0.161400        0.317900   
max           1.252000              0.291000        0.663800   

       worst fractal dimension       class  
count               569.000000  569.000000  
mean                  0.083946    0.627417  
std                   0.018061    0.483918  
min                   0.055040    0.000000  
25%                   0.071460    0.000000  
50%                   0.080040    1.000000  
75%                   0.092080    1.000000  
max                   0.207500    1.000000  

[8 rows x 31 columns]

In [11]:
#how many malignant and benign?
print(data['class'].value_counts()) #binary variable either 1 or 0

1    357
0    212
Name: class, dtype: int64


In [12]:
#know the target names
print(cancer_ds.target_names)

['malignant' 'benign']


In [13]:
data.groupby('class').mean()

mean radius  mean texture  mean perimeter   mean area  mean smoothness  \
class                                                                           
0        17.462830     21.604906      115.365377  978.376415         0.102898   
1        12.146524     17.914762       78.075406  462.790196         0.092478   

       mean compactness  mean concavity  mean concave points  mean symmetry  \
class                                                                         
0              0.145188        0.160775             0.087990       0.192909   
1              0.080085        0.046058             0.025717       0.174186   

       mean fractal dimension  ...  worst radius  worst texture  \
class                          ...                                
0                    0.062680  ...     21.134811      29.318208   
1                    0.062867  ...     13.379801      23.515070   

       worst perimeter   worst area  worst smoothness  worst compactness  \
class                                                                      
0           141.370330  1422.286321          0.144845           0.374824   
1            87.005938   558.899440          0.124959           0.182673   

       worst concavity  worst concave points  worst symmetry  \
class                                                          
0             0.450606              0.182237        0.323468   
1             0.166238              0.074444        0.270246   

       worst fractal dimension  
class                           
0                     0.091530  
1                     0.079442  

[2 rows x 30 columns]

In [14]:
data.groupby('mean area').mean()

mean radius  mean texture  mean perimeter  mean smoothness  \
mean area                                                               
143.5            6.981         13.43           43.79          0.11700   
170.4            7.691         25.44           48.34          0.08668   
178.8            7.729         25.49           47.98          0.08098   
181.0            7.760         24.54           47.92          0.05263   
201.9            8.196         16.84           51.71          0.08600   
...                ...           ...             ...              ...   
1878.0          25.220         24.91          171.50          0.10630   
2010.0          25.730         17.46          174.20          0.11490   
2250.0          27.220         21.87          182.10          0.10940   
2499.0          28.110         18.47          188.50          0.11420   
2501.0          27.420         26.27          186.90          0.10840   

           mean compactness  mean concavity  mean concave points  \
mean area                                                          
143.5               0.07568         0.00000             0.000000   
170.4               0.11990         0.09252             0.013640   
178.8               0.04878         0.00000             0.000000   
181.0               0.04362         0.00000             0.000000   
201.9               0.05943         0.01588             0.005917   
...                     ...             ...                  ...   
1878.0              0.26650         0.33390             0.184500   
2010.0              0.23630         0.33680             0.191300   
2250.0              0.19140         0.28710             0.187800   
2499.0              0.15160         0.32010             0.159500   
2501.0              0.19880         0.36350             0.168900   

           mean symmetry  mean fractal dimension  radius error  ...  \
mean area                                                       ...   
143.5             0.1930                 0.07818        0.2241  ...   
170.4             0.2037                 0.07751        0.2196  ...   
178.8             0.1870                 0.07285        0.3777  ...   
181.0             0.1587                 0.05884        0.3857  ...   
201.9             0.1769                 0.06503        0.1563  ...   
...                  ...                     ...           ...  ...   
1878.0            0.1829                 0.06782        0.8973  ...   
2010.0            0.1956                 0.06121        0.9948  ...   
2250.0            0.1800                 0.05770        0.8361  ...   
2499.0            0.1648                 0.05525        2.8730  ...   
2501.0            0.2061                 0.05623        2.5470  ...   

           worst texture  worst perimeter  worst area  worst smoothness  \
mean area                                                                 
143.5              19.54            50.41       185.2           0.15840   
170.4              31.89            54.49       223.6           0.15960   
178.8              30.92            57.17       248.0           0.12560   
181.0              30.37            59.16       268.6           0.08996   
201.9              21.96            57.26       242.2           0.12970   
...                  ...              ...         ...               ...   
1878.0             33.62           211.70      2562.0           0.15730   
2010.0             23.58           229.30      3234.0           0.15300   
2250.0             32.85           220.80      3216.0           0.14720   
2499.0             18.47           188.50      2499.0           0.11420   
2501.0             31.37           251.20      4254.0           0.13570   

           worst compactness  worst concavity  worst concave points  \
mean area                                                             
143.5                0.12020           0.0000               0.00000   
170.4                0.30640           0.3393               0.0

train test split

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X = data.drop('class', axis=1)
Y = data['class']

In [73]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.1, random_state = 42)

In [56]:
print(Y.shape, Y_train.shape, Y_test.shape)

(569,) (512,) (57,)


# random_state

If there is no random_state provided the system will use a random_state that is generated internally. So, when we run the program multiple times we might see different train/test data points and the behavior will be unpredictable. In case, we have an issue with our model we will not be able to recreate it as we do not know the random number that was generated when we ran the program.

In [47]:
Y_train # Without random state

263    0
434    1
320    1
474    1
416    1
      ..
273    1
52     1
114    1
398    1
502    1
Name: class, Length: 512, dtype: int32

In [60]:
Y_train # Another epoch Without random state

20     1
55     1
467    1
136    1
354    1
      ..
266    1
512    0
377    1
423    1
255    0
Name: class, Length: 512, dtype: int32

To avoid getting different values for train and test every time, we use random_state. This will also have an impact on the evaluation metrics as if the random_state is not selected the values from the evaluation will differ. The values of random_state variable can be any integer, 0 and 1 are the most common values used. You can select your own value. Assume it as a shuffle of cards were, after the first shuffle that's random state 1 the after the second shuffle that's random state 2 etc.

In [57]:
Y_train # With random_state = 10

535    0
338    1
503    0
26     0
158    1
      ..
350    1
357    1
206    1
560    1
416    1
Name: class, Length: 512, dtype: int32

In [58]:
Y_train # Another epoch With random_state = 10, we will get the same set of values

535    0
338    1
503    0
26     0
158    1
      ..
350    1
357    1
206    1
560    1
416    1
Name: class, Length: 512, dtype: int32

In [62]:
Y_train # With random_state = 42

413    1
517    0
245    1
102    1
28     0
      ..
509    0
230    0
354    1
103    1
248    1
Name: class, Length: 512, dtype: int32

In [63]:
Y_train # Another epoch With random_state = 42

413    1
517    0
245    1
102    1
28     0
      ..
509    0
230    0
354    1
103    1
248    1
Name: class, Length: 512, dtype: int32

# Stratify

Stratify parameter makes a split so that the proportion of values in the sample produced will be the same as the proportion of values provided to parameter stratify.

For example, if variable y is a binary categorical variable with values 0 and 1 and there are 25% of zeros and 75% of ones, stratify = y will make sure that your random split has 25% of 0's and 75% of 1's.

Suppose a scenario in which you have 100 binary(0,1) datasets of a cancer patient and you have splitted it into 80% as train_data and 20% as test_data. And by default in test_data, you get 15 values as " 1 " and 5 values as 0, So it will be a quite biased data_set. In order to avoid this situation, we use "stratify" to provide a set of common relationship between training and testing dataset

In [68]:
Y.value_counts() # Ratio of 1 is to 0 in Y is 1.6

1    357
0    212
Name: class, dtype: int64

With Stratify

In [70]:
Y_train.value_counts() #with startify
                      # Ratio of 1 is to 0 in Y_train is 1.6

1    321
0    191
Name: class, dtype: int64

In [71]:
Y_test.value_counts() # Ratio of 1 is to 0 in Y_test is 1.6

1    36
0    21
Name: class, dtype: int64

Without Stratify

In [74]:
Y_train.value_counts() #without startify
                      # Ratio of 1 is to 0 in Y is 1.6

1    317
0    195
Name: class, dtype: int64

In [75]:
Y_test.value_counts() # Ratio of 1 is to 0 in Y is 2.3

1    40
0    17
Name: class, dtype: int64

If we dont use stratify variable then we get the composition of the train and test sets differ, and this is not desirable and it makes the data biased